version: '3.4'

services:
  loadbalancer:
    image: ${DOCKER_REGISTRY-}loadbalancer
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile

  searchapi:
    image: ${DOCKER_REGISTRY-}searchapi
    build:
      context: .
      dockerfile: SearchAPI/Dockerfile
    volumes:
      - D:/Main/DockerVolumes:/data
    deploy:
        replicas: 3
    depends_on:
      - loadbalancer

  webclient:
    image: ${DOCKER_REGISTRY-}webclient
    build:
      context: .
      dockerfile: WebClient/Dockerfile
    depends_on:
      - loadbalancer

