version: '3.4'

services:
  loadbalancer:
    image: ${DOCKER_REGISTRY-}loadbalancer
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile

  searchapi:
    image: ${DOCKER_REGISTRY-}searchapi
    build:
      context: .
      dockerfile: SearchAPI/Dockerfile
    volumes:
      - D:/Main/DockerVolumes:/data

  websearch:
    image: ${DOCKER_REGISTRY-}websearch
    build:
      context: .
      dockerfile: WebSearch/Dockerfile

